# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:22
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('image', models.ImageField(default='https://.s3.amazonaws.com/media//img/flow.jpg', storage=blog.models.MediaS3BotoStorage(), upload_to='img/blog/')),
                ('body', models.TextField()),
                ('favorite', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['posted', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('posted', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
