# Generated by Django 2.2.2 on 2019-06-13 17:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='/media//img/flow.jpg', storage=blog.models.MediaS3BotoStorage(), upload_to='img/blog/'),
        ),
    ]
